provider:
  name: faas
functions:
  gotag-fn:
    lang: golang-http
    handler: ./gotag-fn
    image: embano1/gotag-fn:0.1
    environment:
      VC: 
      VC_USER: 
      VC_PASS: 
      TAG_URN: 
      INSECURE: false
    annotations:
      topic: vm.powered.on